pub const StorageError = error{
    DuplicateKey,
    KeyNotFound,
    TableFull,
    TableNotFound,
    TableAlreadyExists,
    PageOutOfBounds,
    PageNotFound,
    IncompleteRead,
    OutOfMemory,
    ColumnNotFound,
    TypeMismatch,
    NullValueNotAllowed,
    TableNoPrimaryKey,
    InvalidDatabaseFile,
};
