const std = @import("std");

pub const TokenType = enum {
    illegal,
    eof,
    ws,

    ident,
    int,
    float,
    string,

    eq,
    neq,
    lt,
    gt,
    lte,
    gte,
    plus,
    minus,
    asterisk,
    slash,

    comma,
    semicolon,
    lparen,
    rparen,
    dot,

    select,
    from,
    where,
    insert,
    into,
    values,
    create,
    table,
    delete,
    update,
    set,
    @"and",
    @"or",
    not,
    null,
    primary,
    key,
    integer,
    text,
    real,
    blob,
    boolean,
    true,
    false,
    date,
    time,
    datetime,
    order,
    by,
    asc,
    desc,
    limit,
    offset,
    drop,
    @"if",
    exists,
    index,
    unique,
    on,
    begin,
    commit,
    rollback,
    transaction,
    savepoint,
    release,
    to,
    isolation,
    level,
    read,
    uncommitted,
    committed,
    repeatable,
    serializable,
    join,
    inner,
    left,
    right,
    cross,
    outer,
    distinct,
    group,
    having,
    count,
    sum,
    avg,
    min,
    max,
    between,
    in,
    like,
    is,
    case,
    when,
    then,
    @"else",
    end,
    as,
    @"union",
    all,
    alter,
    add,
    column,
    rename,
    upper,
    lower,
    length,
    substr,
    concat,
    trim,
    check,
    abs,
    round,
    floor,
    ceil,
    coalesce,
    nullif,
    ifnull,

    pub fn toString(self: TokenType) []const u8 {
        return switch (self) {
            .illegal => "ILLEGAL",
            .eof => "EOF",
            .ws => "WS",
            .ident => "IDENT",
            .int => "INT",
            .float => "FLOAT",
            .string => "STRING",
            .eq => "=",
            .neq => "!=",
            .lt => "<",
            .gt => ">",
            .lte => "<=",
            .gte => ">=",
            .plus => "+",
            .minus => "-",
            .asterisk => "*",
            .slash => "/",
            .comma => ",",
            .semicolon => ";",
            .lparen => "(",
            .rparen => ")",
            .dot => ".",
            .select => "SELECT",
            .from => "FROM",
            .where => "WHERE",
            .insert => "INSERT",
            .into => "INTO",
            .values => "VALUES",
            .create => "CREATE",
            .table => "TABLE",
            .delete => "DELETE",
            .update => "UPDATE",
            .set => "SET",
            .@"and" => "AND",
            .@"or" => "OR",
            .not => "NOT",
            .null => "NULL",
            .primary => "PRIMARY",
            .key => "KEY",
            .integer => "INTEGER",
            .text => "TEXT",
            .real => "REAL",
            .blob => "BLOB",
            .boolean => "BOOLEAN",
            .true => "TRUE",
            .false => "FALSE",
            .date => "DATE",
            .time => "TIME",
            .datetime => "DATETIME",
            .order => "ORDER",
            .by => "BY",
            .asc => "ASC",
            .desc => "DESC",
            .limit => "LIMIT",
            .offset => "OFFSET",
            .drop => "DROP",
            .@"if" => "IF",
            .exists => "EXISTS",
            .index => "INDEX",
            .unique => "UNIQUE",
            .on => "ON",
            .begin => "BEGIN",
            .commit => "COMMIT",
            .rollback => "ROLLBACK",
            .transaction => "TRANSACTION",
            .savepoint => "SAVEPOINT",
            .release => "RELEASE",
            .to => "TO",
            .isolation => "ISOLATION",
            .level => "LEVEL",
            .read => "READ",
            .uncommitted => "UNCOMMITTED",
            .committed => "COMMITTED",
            .repeatable => "REPEATABLE",
            .serializable => "SERIALIZABLE",
            .join => "JOIN",
            .inner => "INNER",
            .left => "LEFT",
            .right => "RIGHT",
            .cross => "CROSS",
            .outer => "OUTER",
            .distinct => "DISTINCT",
            .group => "GROUP",
            .having => "HAVING",
            .count => "COUNT",
            .sum => "SUM",
            .avg => "AVG",
            .min => "MIN",
            .max => "MAX",
            .between => "BETWEEN",
            .in => "IN",
            .like => "LIKE",
            .is => "IS",
            .case => "CASE",
            .when => "WHEN",
            .then => "THEN",
            .@"else" => "ELSE",
            .end => "END",
            .as => "AS",
            .@"union" => "UNION",
            .all => "ALL",
            .alter => "ALTER",
            .add => "ADD",
            .column => "COLUMN",
            .rename => "RENAME",
            .upper => "UPPER",
            .lower => "LOWER",
            .length => "LENGTH",
            .substr => "SUBSTR",
            .concat => "CONCAT",
            .trim => "TRIM",
            .check => "CHECK",
            .abs => "ABS",
            .round => "ROUND",
            .floor => "FLOOR",
            .ceil => "CEIL",
            .coalesce => "COALESCE",
            .nullif => "NULLIF",
            .ifnull => "IFNULL",
        };
    }
};

pub const Token = struct {
    type: TokenType,
    literal: []const u8,
    line: usize,
    column: usize,
};

const keywords = std.StaticStringMap(TokenType).initComptime(.{
    .{ "SELECT", .select },
    .{ "FROM", .from },
    .{ "WHERE", .where },
    .{ "INSERT", .insert },
    .{ "INTO", .into },
    .{ "VALUES", .values },
    .{ "CREATE", .create },
    .{ "TABLE", .table },
    .{ "DELETE", .delete },
    .{ "UPDATE", .update },
    .{ "SET", .set },
    .{ "AND", .@"and" },
    .{ "OR", .@"or" },
    .{ "NOT", .not },
    .{ "NULL", .null },
    .{ "PRIMARY", .primary },
    .{ "KEY", .key },
    .{ "INTEGER", .integer },
    .{ "TEXT", .text },
    .{ "REAL", .real },
    .{ "BLOB", .blob },
    .{ "BOOLEAN", .boolean },
    .{ "TRUE", .true },
    .{ "FALSE", .false },
    .{ "DATE", .date },
    .{ "TIME", .time },
    .{ "DATETIME", .datetime },
    .{ "ORDER", .order },
    .{ "BY", .by },
    .{ "ASC", .asc },
    .{ "DESC", .desc },
    .{ "LIMIT", .limit },
    .{ "OFFSET", .offset },
    .{ "DROP", .drop },
    .{ "IF", .@"if" },
    .{ "EXISTS", .exists },
    .{ "INDEX", .index },
    .{ "UNIQUE", .unique },
    .{ "ON", .on },
    .{ "BEGIN", .begin },
    .{ "COMMIT", .commit },
    .{ "ROLLBACK", .rollback },
    .{ "TRANSACTION", .transaction },
    .{ "SAVEPOINT", .savepoint },
    .{ "RELEASE", .release },
    .{ "TO", .to },
    .{ "ISOLATION", .isolation },
    .{ "LEVEL", .level },
    .{ "READ", .read },
    .{ "UNCOMMITTED", .uncommitted },
    .{ "COMMITTED", .committed },
    .{ "REPEATABLE", .repeatable },
    .{ "SERIALIZABLE", .serializable },
    .{ "JOIN", .join },
    .{ "INNER", .inner },
    .{ "LEFT", .left },
    .{ "RIGHT", .right },
    .{ "CROSS", .cross },
    .{ "OUTER", .outer },
    .{ "DISTINCT", .distinct },
    .{ "GROUP", .group },
    .{ "HAVING", .having },
    .{ "COUNT", .count },
    .{ "SUM", .sum },
    .{ "AVG", .avg },
    .{ "MIN", .min },
    .{ "MAX", .max },
    .{ "BETWEEN", .between },
    .{ "IN", .in },
    .{ "LIKE", .like },
    .{ "IS", .is },
    .{ "CASE", .case },
    .{ "WHEN", .when },
    .{ "THEN", .then },
    .{ "ELSE", .@"else" },
    .{ "END", .end },
    .{ "AS", .as },
    .{ "UNION", .@"union" },
    .{ "ALL", .all },
    .{ "ALTER", .alter },
    .{ "ADD", .add },
    .{ "COLUMN", .column },
    .{ "RENAME", .rename },
    .{ "UPPER", .upper },
    .{ "LOWER", .lower },
    .{ "LENGTH", .length },
    .{ "SUBSTR", .substr },
    .{ "CONCAT", .concat },
    .{ "TRIM", .trim },
    .{ "CHECK", .check },
    .{ "ABS", .abs },
    .{ "ROUND", .round },
    .{ "FLOOR", .floor },
    .{ "CEIL", .ceil },
    .{ "COALESCE", .coalesce },
    .{ "NULLIF", .nullif },
    .{ "IFNULL", .ifnull },
});

pub fn lookup_ident(ident: []const u8) TokenType {
    var upper_buf: [64]u8 = undefined;
    const len = @min(ident.len, upper_buf.len);
    const upper = std.ascii.upperString(upper_buf[0..len], ident[0..len]);

    return keywords.get(upper) orelse .ident;
}

test "lookup_ident" {
    try std.testing.expect(lookup_ident("select") == .select);
    try std.testing.expect(lookup_ident("FROM") == .from);
    try std.testing.expect(lookup_ident("Where") == .where);
    try std.testing.expect(lookup_ident("my_column") == .ident);
    try std.testing.expect(lookup_ident("TableName") == .ident);
}
